# Generated by Django 5.2.1 on 2025-05-30 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pemesan', models.CharField(max_length=100)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField(choices=[(1, 'Menunggu Pembayaran'), (2, 'Diproses'), (3, 'Selesai'), (4, 'Dibatalkan')], default=1)),
                ('tanggal_pesan', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetailPesanan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesanan.pesanan')),
            ],
        ),
    ]
