# Generated by Django 5.2.1 on 2025-05-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.IntegerField()),
                ('jenis', models.IntegerField(choices=[(1, 'Makanan'), (2, 'Minuman')], default=1)),
                ('image', models.ImageField(upload_to='menus/')),
            ],
        ),
    ]
